# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 19:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='data',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
