# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 19:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_of_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
