# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_auto_20170523_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.ManyToManyField(to='elearning.Content'),
        ),
    ]
