# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_auto_20170516_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elearning.NasUser'),
        ),
    ]
