# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_auto_20170510_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='start',
            field=models.DateField(),
        ),
    ]
