# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('elearning', '0004_auto_20170524_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nasuser',
            name='type',
        ),
        migrations.RemoveField(
            model_name='nasuser',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='NasUser',
        ),
    ]
