# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_remove_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='end',
            field=models.DateField(default=datetime.date(2017, 5, 11)),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_of_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='start',
            field=models.DateField(default=datetime.date(2017, 5, 11)),
        ),
    ]
