# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0008_auto_20170511_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TEST', to='elearning.Groups'),
        ),
    ]
