# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0008_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course_list',
            field=models.ManyToManyField(blank=True, null=True, to='elearning.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='programmes',
            field=models.ManyToManyField(blank=True, null=True, to='elearning.Program'),
        ),
    ]
