# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0009_auto_20170518_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
