# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0010_auto_20170511_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.Groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.Groups'),
        ),
    ]
