# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0014_auto_20170512_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number_of_people',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
